last_change = 2025-08-22T18:24:27.894856Z
addr = 0x6fd
size = 0x20
name = "old_name"
artifact_type = "Function"

[header]
last_change = 2025-08-22T18:24:27.894856Z
name = "old_name"
addr = 0x6fd

[header.args]
