[metadata]
addr = 0x40071d
size = 0xb8
last_change = 2022-12-20T21:59:59.534734Z

[header]
last_change = 2022-12-20T21:59:59.534734Z
name = "mahaloz_main"
addr = 0x40071d
type = "long"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "args"
type = "char **"
size = 0x8

[header.args.2]
offset = 0x2
name = "a3"
type = "char **"
size = 0x8
