last_change = 2023-06-01T22:39:55.880270Z
addr = 0x400530
size = 0x0
name = "read"
type = "typedef ssize_t __ssize_t"

[header]
name = "read"
addr = 0x400530
type = "typedef ssize_t __ssize_t"

[header.args]
