[metadata]
addr = 0x400664
size = 0x0

[header]
name = "authenicate_user"
addr = 0x400664
type = "_BOOL8"

[header.args.0]
offset = 0x0
name = "controlled_file"
type = "const char *"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "const char *"
size = 0x8
