last_change = 2023-10-17T23:45:24.298444Z
addr = 0x40071d
size = 0xb8
name = "main"

[header]
name = "main"
addr = 0x40071d

[header.args]

[stack_vars.-0x18]
offset = -24
name = "another_stack_var2"
type = "undefined[8]"
size = 0x8
addr = 0x40071d

[stack_vars.-0x2c]
offset = -44
name = "flipouts_variable"
type = "int"
size = 0x4
addr = 0x40071d

[stack_vars.-0x28]
offset = -40
name = "special_var"
type = "undefined[8]"
size = 0x8
addr = 0x40071d

[stack_vars.-0x20]
offset = -32
name = "test_int"
type = "int"
size = 0x4
addr = 0x40071d

[stack_vars.-0x10]
offset = -16
name = "test_stack_var"
type = "undefined"
size = 0x1
addr = 0x40071d
