last_change = 2023-06-01T22:39:56.466472Z
addr = 0x400880
size = 0x0
name = "__do_global_ctors_aux"
type = "undefined"

[header]
name = "__do_global_ctors_aux"
addr = 0x400880
type = "undefined"

[header.args]
