last_change = 2023-06-01T22:39:56.633678Z
addr = 0x602010
size = 0x0
name = "read"
type = "typedef ssize_t __ssize_t"

[header]
name = "read"
addr = 0x602010
type = "typedef ssize_t __ssize_t"

[header.args]
