[0x400664]
addr = 0x400664
func_addr = 0x400664
comment = "This function is the main function that \ndoes authentication for the user.\nYou only need to know the sneaky_password! \n"
decompiled = false
