user = "flipout"
version = "4.4.2"
last_push_time = 2024-07-31T23:01:05.789576Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Struct: mahaloz_struct membs=0 (0x0)> from flipout"
