user = "flipout"
version = "4.4.2"
last_push_time = 2023-10-25T22:52:13.973105Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Struct: mahaloz_struct membs=4 (0x10)> from mahaloz"
