user = "flipout"
version = "4.4.2"
last_push_time = 2024-08-11T18:15:29.878622Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Struct: mahaloz_struct membs=2 (0x2)> from flipout"
