user = "flipout"
version = "4.4.2"
last_push_time = 2024-08-11T18:05:59.606596Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Struct: another_one membs=0 (0x0)> from flipout"
