user = "flipout"
version = "4.4.2"
last_push_time = 2024-07-31T20:28:32.258232Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <Struct: mahaloz_struct2 membs=0 (0x1)>"
