last_change = 2023-10-25T22:52:13.973105Z
name = "another_one"
size = 0xd

[members.0x0]
name = "integer"
offset = 0x0
type = "int"
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = "char"
size = 0x1

[members.0x5]
name = "field_5"
offset = 0x5
type = "longlong"
size = 0x8
