[metadata]
name = "another_one"
size = 0xd
last_change = 2023-10-25T18:37:12.353669Z

[members.0x0]
name = "integer"
offset = 0x0
type = "int"
size = 0x4

[members.0x4]
name = "char"
offset = 0x4
type = "char"
size = 0x1

[members.0x5]
name = "long num"
offset = 0x5
type = "longlong"
size = 0x8
