last_change = 2024-08-11T18:15:29.878622Z
name = "mahaloz_struct"
size = 0x2

[members.0x0]
name = "field_0"
offset = 0x0
type = ""
size = 0x1

[members.0x1]
name = "field_1"
offset = 0x1
type = ""
size = 0x1
