last_change = 2024-07-31T19:02:50.609201Z
name = "mahaloz_struct2"
size = 0x10

[members.0x0]
name = "some_thing"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = ""
size = 0x4

[members.0x8]
name = "field_8"
offset = 0x8
type = ""
size = 0x4

[members.0xc]
name = "field_C"
offset = 0xc
type = ""
size = 0x4
