last_change = 2024-08-11T18:11:40.691690Z
name = "mahaloz_struct"
size = 0xc

[members.0x0]
name = "field_0"
offset = 0x0
type = ""
size = 0x8

[members.0x8]
name = "field_8"
offset = 0x8
type = ""
size = 0x4
