last_change = 2024-07-31T22:59:31.377623Z
name = "mahaloz_struct"
size = 0x10

[members.0x0]
name = "some_thing"
offset = 0x0
type = "char4"
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = "char4"
size = 0x4

[members.0x8]
name = "field_8"
offset = 0x8
type = "char4"
size = 0x4

[members.0xc]
name = "field_C"
offset = 0xc
type = "char4"
size = 0x4
