last_change = 2024-07-31T23:01:05.784491Z
name = "mahaloz_struct"
size = 0xc

[members.0x0]
name = "some_thing"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = ""
size = 0x4

[members.0x8]
name = "field_8"
offset = 0x8
type = ""
size = 0x4
