last_change = 2024-07-31T19:35:19.064985Z
name = "mahaloz_struct2"
size = 0x8

[members.0x0]
name = "some_thing"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = ""
size = 0x4
