[metadata]
name = "mahaloz_struct"
size = 0x5
last_change = 2022-12-20T22:00:41.583239Z

[members.0x0]
name = "field_0"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = ""
size = 0x1
