last_change = 2024-08-11T18:11:30.037189Z
name = "mahaloz_struct"
size = 0xc

[members.0x0]
name = "field_0"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = ""
size = 0x8
